Create/app apartments templates
liis-dev-team/simplehome-openapi pull request #3
Opened 2023-12-13 19:57 UTC by Machalkas

2023-12-14 09:51 UTC, 0nliner requested changes

2023-12-14 09:51 UTC, 0nliner commented on openapi/openapi.yaml
> +    $ref: ./paths/apartment_templates/AdminApartmentTemplates.yaml
давай удалим папку paths. Её содержимое перенесём в routes. routes более очевидное название

2023-12-14 09:51 UTC, 0nliner commented on openapi/schemas/action_templates/ScenarioTemplateWithDeviceId.yaml
> +properties:
очень подозрительно, что нигде нет поля required. Это важно

2023-12-14 09:51 UTC, 0nliner commented on openapi/schemas/core/filters/datetime_query_filter.yaml
> +CreateBeforeFilter:
не сможешь переиспользовать данные фильтры из-за наличия имён у них. Они должны быть разбиты по разным файлам

2023-12-14 09:51 UTC, 0nliner commented on openapi/schemas/core/schemas/listOfIds.yaml
> +type: object
строка импорта этого объекта будет длиннее, чем написание example. Смысла не имеет, считаю

2023-12-14 13:41 UTC, Machalkas commented on openapi/schemas/action_templates/ScenarioTemplateWithDeviceId.yaml
> +properties:
Да у нас их считай нигде нет
![image](https://github.com/liis-dev-team/simplehome-openapi/assets/52866342/32d5f9ae-0a44-48fd-bb83-10b4a3fe37b1)

2023-12-14 15:19 UTC, Machalkas commented on openapi/schemas/action_templates/ScenarioTemplateWithDeviceId.yaml
> +properties:
добавил

2023-12-15 08:10 UTC, 0nliner commented on openapi/schemas/core/filters/datetime_query_filter.yaml
> +CreateBeforeFilter:
не видел, что можно переиспользовать параметры

2023-12-15 08:14 UTC, merged